### ISSUE TITLE
Laravel auth

### ISSUE THREAD

**Issue by aliqasemzadeh** [rehhouari/vite-alpine-pwa#1]
Hi 
Please add laravel scantum auth.

**Comment by rehhouari** [comment]
Hello, thanks for the suggestion
I've been unable to work on anything for a while but looking for ways to do so, can't give an exact date however.

And for Sanctum I'm not familiar with Laravel at all so I'm not sure I can do that
Feel free to clone and try around with it add the integration.
I also don't think it'll be beneficial for this template since it focus on js-only web apps.
If you manage to integrate it I'll gladly list your fork in the readme ^^
